name: dart_build_script
version: 0.0.1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  crypto: ^3.0.1
  dio: ^4.0.0
  sprintf: ^6.0.0

dev_dependencies:
  pedantic: ^1.9.2